// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV83Zu9aSW0ebN9IAkcUiyEPZWQgnoc3o',
    appId: '1:269176635691:android:1ee8548edc98157127056e',
    messagingSenderId: '269176635691',
    projectId: 'mine-514b8',
    databaseURL: 'https://mine-514b8-default-rtdb.firebaseio.com',
    storageBucket: 'mine-514b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFp9f5qfFIbz4rzTNTHWYldsIYesEf_zw',
    appId: '1:269176635691:ios:719a6f79b25e60f227056e',
    messagingSenderId: '269176635691',
    projectId: 'mine-514b8',
    databaseURL: 'https://mine-514b8-default-rtdb.firebaseio.com',
    storageBucket: 'mine-514b8.appspot.com',
    androidClientId: '269176635691-gd25mho8stplociqc87guiftig0q5c09.apps.googleusercontent.com',
    iosClientId: '269176635691-bdap8r5md2ihaps3eamtl1kdedku39vp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
